---
apiVersion: v1
kind: Service
metadata:
  name: uber
spec:
  selector:
    app: uber
  ports:
  - port: 80
    name: http-uber
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uber
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: uber
        image: yosz328/uber_service
        ports:
        - name: http-api
          containerPort: 8082
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
